# Project-wide Gradle settings.
# Force Gradle to use JDK 17 (Gradle 8.9 does not support JVM 23–25).
#org.gradle.java.home=D:\\devtools\\jdk17\\jdk-17.0.20+8
org.gradle.jvmargs=-Xmx2560m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
